version: '3.8'

services:
  prestashop:
    image: prestashop/prestashop:latest
    ports:
      - "80:80"
    environment:
      - DB_SERVER=db
      - DB_NAME=prestashopDB
      - DB_USER=usuarioprestashop
      - DB_PASSWD=password
      - PS_INSTALL_AUTO=0
    volumes:
      - /data/prestashop:/var/www/html
    depends_on:
      - db
    networks:
      - prestashop-net
    restart: always

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashopDB
      - MYSQL_USER=usuarioprestashop
      - MYSQL_PASSWORD=password
    volumes:
      - /data/prestashop_DB:/var/lib/mysql
    networks:
      - prestashop-net
    restart: always

networks:
  prestashop-net:
    driver: bridge

