<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPE8c0XW\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPE8c0XW/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerPE8c0XW.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerPE8c0XW\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerPE8c0XW\appAppKernelProdContainer([
    'container.build_hash' => 'PE8c0XW',
    'container.build_id' => '1479a1fe',
    'container.build_time' => 1718400094,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPE8c0XW');
